version: '3.7'
services:
  postgres:
    image: postgres
    environment:
     - POSTGRES_PASSWORD=example
     - POSTGRES_USER=postgres
     - PGDATA=/var/lib/postgresql/data
    port:
     - 5432:5432
  cashwebd:
    image: cashwebd
    build: 
      context: ./